FROM jlesage/jdownloader-2:latest

COPY 56-myjdownloader-direct-connection.sh /etc/cont-init.d/56-myjdownloader-direct-connection.sh
RUN chmod +x /etc/cont-init.d/56-myjdownloader-direct-connection.sh
